ingress:
  domainName: mydomainname
  annotations:
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
      - mydomainname
      secretName: letsencrypt-myapp