name: Build an image
description: Builds a simple docker image with ./Dockerfile
inputs:
  docker_username:
    description: Docker-registry username
    required: true
  docker_password:
    description: Docker-registry password
    required: true
  image_names:
    description: Docker image name
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ inputs.image_names }}
