name: Build an image
description: Builds a simple docker image with ./Dockerfile
inputs:
  kubeconfig:
    description: A kubeconfig file content. You know, for Helm
    required: true
  branch:
    description: Docker-registry password
    required: true
  domain_name:
    description: Docker image name
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.33.1'
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.17.3'
    - name: Extract kubeconfig
      shell: bash
      run: |
        echo "${{ inputs.kubeconfig }}" > $HOME/config
    - name: Install the app
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.branch }} ./manifests-helm/chart \
        --kubeconfig $HOME/config \
        --namespace ${{ inputs.branch }} --create-namespace \
        --values manifests-helm/values/dev.yaml \
        --set "ingress.domainName=${{ inputs.domain_name }}" \
        --set "ingress.tls[0].hosts={${{ inputs.domain_name }}}" \
        --set "image.tag=${{ inputs.branch }}-${{ github.sha }}" \
        --wait --timeout 5m