name: Build an image
description: Builds a simple docker image with ./Dockerfile
inputs:
  kubeconfig:
    description: A kubeconfig file content. You know, for Helm
    required: true
  domain_name:
    description: Docker image name
    required: true
  values_path:
    description: A path to a values.yaml file
    required: true
  namespace:
    description: A namespace for a chart to be deployed to
    required: false
  release_name:
    description: A release name for a Helm chart
    required: false
  image_tag: 
    description: A custom tag of an installed image
    required: false
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.33.1'
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.17.3'
    - name: Extract kubeconfig
      shell: bash
      run: |
        echo "${{ inputs.kubeconfig }}" > $HOME/config
    - name: Install the app
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.release_name || 'myapp' }} ./manifests-helm/chart \
        --kubeconfig $HOME/config \
        --namespace ${{ inputs.namespace || 'default' }} --create-namespace \
        --values ${{ inputs.values_path }} \
        --set "ingress.domainName=${{ inputs.domain_name }}" \
        --set "ingress.tls[0].hosts={${{ inputs.domain_name }}}" \
        --set "image.tag=${{ inputs.image_tag || 'stage-latest') }}" \
        --wait --timeout 5m