on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.3'
      - name: Extract kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/config

      - name: Check branches older then a week
        run: |
          git fetch --all --prune --depth=1
          week_ago=$(date -d '7 days ago' +%s)

          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
            echo $branch
          done


