name: Cleanup branches after deletion

on: delete
jobs:
  cleanup:
    if: ${{ (github.event.ref_type == 'branch') && (github.event.ref != 'main') && (github.event.ref != 'stage') }}
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.3'
      - name: Extract kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/config

      - name: Delete the env after branch was deleted
        run: |
          KUBECONFIG=$HOME/config kubectl delete ns ${{ github.event.ref }} --ignore-not-found

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while deleting an environment

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
