on:
  push:
    branches-ignore:
      - main
      - stage

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-latest

  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.3'
      - name: Extract kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      - name: Install the app
        run: |
          helm upgrade --install dev-${{ env.BRANCH_NAME }} ./manifests/base \
          --namespace dev-${{ env.BRANCH_NAME }} --create-namespace \
          --values ./chart/values-production.yaml
