name: Dev - Build & Deploy

on:
  push:
    branches-ignore:
      - main
      - stage
    paths-ignore:
      - '.gitignore'
      - 'README.md'

env:
  TAG_BASE: ${{ github.ref_name }} 

jobs:
  docker-build:
    if: ${{ github.ref_name != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build an image
        uses: ./.github/actions/basic-app-build
        with:
          docker_username: ${{ vars.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_names: |
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.TAG_BASE }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.TAG_BASE }}-latest

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while building the docker image

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    environment:
      name: dev
      url: https://${{ env.TAG_BASE }}.${{ vars.BASE_DOMAIN_NAME }}
    steps:
      - uses: actions/checkout@v5
      - name: Deploy a Helm-chart
        uses: ./.github/actions/basic-app-deploy
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          domain_name: ${{ env.TAG_BASE }}.${{ vars.BASE_DOMAIN_NAME }}
          values_path: manifests-helm/values/dev.yaml
          namespace: ${{ env.TAG_BASE }}
          release_name: ${{ env.TAG_BASE }}
          image_tag: ${{ env.TAG_BASE }}-${{ github.sha }}


      - name: Notify SUCCESS in Telegram
        if: success()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            UPDATE
            Env: <code>${{ env.TAG_BASE }}</code> 

            Link: https://${{ env.TAG_BASE }}.${{ vars.BASE_DOMAIN_NAME }}

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while deploying a <code>${{ env.TAG_BASE }}</code> branch

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
