on:
  push:
    branches-ignore:
      - main
      - stage

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  BASE_DOMAIN_NAME: jb-assignment.shakhtarov.me

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-latest

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            An error occured while building the docker image

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v5
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.3'
      - name: Extract kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/config
      - name: Install the app
        run: |
          helm upgrade --install ${{ env.BRANCH_NAME }} ./manifests-helm/chart \
          --kubeconfig $HOME/config \
          --namespace ${{ env.BRANCH_NAME }} --create-namespace \
          --values manifests-helm/values/dev.yaml \
          --set "ingress.domainName=${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN_NAME }}" \
          --set "ingress.tls[0].hosts={${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN_NAME }}}" \
          --set "image.tag=${{ env.BRANCH_NAME }}-${{ github.sha }}"

      - name: Notify SUCCESS in Telegram
        if: success()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            A new DEV environment was just updated for <code>${{ env.BRANCH_NAME }}</code>

            You can check it out here: https://${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN_NAME }}
      - name: Notify SUCCESS in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            An error occured while deploying a <code>${{ env.BRANCH_NAME }}</code> branch

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
