name: Dev - Build & Deploy

on:
  push:
    branches-ignore:
      - main
      - stage
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      image_tag: ${{ github.ref_name }}-${{ github.sha }}
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: dev
      image_tag: ${{ github.ref_name }}-${{ github.sha }}
      subdomain: ${{ github.ref_name }}
