name: Dev - Build & Deploy

on:
  push:
    paths:
      - 'app/**'
      - 'manifests-helm/**'
    branches-ignore:
      - main
      - stage
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }} 
  BASE_DOMAIN_NAME: jb-assignment.shakhtarov.me

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build an image
        uses: ./.github/actions/basic-app-build
        with:
          docker_username: ${{ vars.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_names: |
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ env.BRANCH_NAME }}-latest

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while building the docker image

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v5
      - name: Deploy a Helm-chart
        uses: ./.github/actions/basic-app-deploy
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          branch: ${{ env.BRANCH_NAME }}
          domain_name: ${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN_NAME }}
          values_path: manifests-helm/values/dev.yaml

      - name: Notify SUCCESS in Telegram
        if: success()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            UPDATE
            Env: <code>${{ env.BRANCH_NAME }}</code> 

            Link: https://${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN_NAME }}

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while deploying a <code>${{ env.BRANCH_NAME }}</code> branch

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
