name: Prod - Deploy

on:
  workflow_run:
    workflows: [Stage - Build & Deploy]
    types:
      - completed    

jobs:
  create-tag-after-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: prod
      url: https://${{ vars.BASE_DOMAIN_NAME }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Re-tag an image for prod
        run: |
          docker buildx imagetools create --tag \
          ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:stage-${{ github.event.workflow_run.head_sha }} \
          ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:main-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: create-tag-after-approve
    steps:
      - uses: actions/checkout@v5
      - name: Deploy a Helm-chart
        uses: ./.github/actions/basic-app-deploy
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          domain_name: ${{ vars.BASE_DOMAIN_NAME }}
          values_path: manifests-helm/values/prod.yaml
          namespace: prod
          release_name: prod
          image_tag: stable-${{ github.event.workflow_run.head_sha }}

      - name: Notify SUCCESS in Telegram
        if: success()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            UPDATE
            Env: <code>prod</code> 

            Link: https://${{ vars.BASE_DOMAIN_NAME }}

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while deploying a <code>prod</code>

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

