name: Prod - Deploy

on:
  workflow_run:
    workflows: [Stage - Build & Deploy]
    types:
      - completed    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://jb-assignment.shakhtarov.me
    steps:
      - uses: actions/checkout@v5
      - name: Deploy a Helm-chart
        uses: ./.github/actions/basic-app-deploy
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          domain_name: jb-assignment.shakhtarov.me
          values_path: manifests-helm/values/prod.yaml
          namespace: prod
          release_name: prod
          image_tag: stable-${{ github.sha }}

      - name: Notify SUCCESS in Telegram
        if: success()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            UPDATE
            Env: <code>prod</code> 

            Link: https://jb-assignment.shakhtarov.me

      - name: Notify FAIL in Telegram
        if: failure()
        uses: ./.github/actions/telegram-notifier
        with:
          telegram_bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          telegram_chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          message_content: |
            ERROR
            An error occured while deploying a <code>prod</code>

            More details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

