name: Stage - Build & Deploy

on:
  push:
    branches:
      - stage
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: ./.github/workflows/general-build.yaml
    secrets: inherit
    with:
      image_tag: ${{ github.base_ref }}-${{ github.sha }}
  deploy:
    needs: build
    uses: ./.github/workflows/general-deploy.yaml
    secrets: inherit
    with:
      environment: stage
      image_tag: ${{ github.base_ref }}-${{ github.sha }}
      subdomain: ${{ github.base_ref }}
  
  run_vulnerability_tests:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/jb-basic-app:${{ github.base_ref }}-${{ github.sha }}
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'


  run_smoke_tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait while SSL certificate is issued
        run: |
          echo "Waiting for a trusted SSL certificate for ${{ github.base_ref }}.${{ vars.BASE_DOMAIN_NAME }} ..."

          for i in {1..30}; do
            if curl -sI "https://${{ github.base_ref }}.${{ vars.BASE_DOMAIN_NAME }}"  >/dev/null 2>&1; then
              echo "✅ Trusted SSL certificate is available for the domain"
              exit 0
            else
              sleep 10
            fi
          done

          echo "❌ Timeout: Trusted SSL certificate did not appear within 5 minutes."
          exit 1

      - name: Really strong test
        run: |
          curl --fail https://${{ github.base_ref }}.${{ vars.BASE_DOMAIN_NAME }}/healthCheck 
